sub:
 - https://bitbucket.org/huwo1/proxy_nodes/raw/b90856fe7cb9c666223f3ad41c87d0e60c711590/proxy.md
 - https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub
 - https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity
 - https://raw.githubusercontent.com/wrfree/free/main/v2
 - https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
 - https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
 - https://raw.githubusercontent.com/adiwzx/freenode/main/adispeed.txt
 - https://raw.githubusercontent.com/freefq/free/master/v2
 - https://raw.githubusercontent.com/xiyaowong/freeFQ/main/v2ray
local: ["into.yaml","../../Clash.yaml"]
